const c = {
	clubName: "ClubKit",
	universityName: "UTSA",
	universityID: {
		name: "ABC123",
		maxLength: 6,
	},
	semesters: {
		current: {
			title: "Fall 2024",
			startDate: new Date("2024-08-24"),
			endDate: new Date("2024-12-31"),
			pointsRequired: 7,
		},
	},
	contactEmail: "tech@acmutsa.org",
	membership: {
		activeThreshold: 7,
	},
	events: {
		idLength: 6,
		checkingInInfo:
			"The membership portal is ACM's new method of tracking member check-ins and awarding points. By simply visiting this page during the event and clicking the Check-in button, you can easily garner points towards your membership for the semester.",
		aboutOrg:
			"ACM is the premier organization on campus for students interested in technology. ACM is dedicated to providing members with opportunities for professional, academic, and social growth outside the classroom in order to prepare students for their career in tech or fuel their interest in the tech field. Anyone who has an interest in technology can join ACM.",
	},
	// TODO: Actually use this instead of hardcoded values in form
	userIdentityOptions: {
		ethnicity: [
			"American Indian or Alaska Native",
			"Asian",
			"Black or African American",
			"Hispanic or Latino",
			"Native Hawaiian or Other Pacific Islander",
			"White",
		],
		gender: [
			"Male",
			"Female",
			"Non-binary",
			"Transgender",
			"Intersex",
			"Prefer not to say",
		],
	},
	calendarLinks: [
		{ title: "google" },
		{ title: "outlook" },
		{ title: "ics", titleOverride: "iCal" },
	],
	streamingLinks: [
		{ title: "twitch", href: "https://www.twitch.tv/acmutsa" },
		{ title: "youtube", href: "https://www.youtube.com/@acmutsa/streams" },
	],
	maxResumeSizeInBytes: 3670016,
	dashPaths: {
		admin: {
			Overview: "/admin",
			Members: "/admin/members",
			Events: "/admin/events",
			Checkins: "/admin/checkins",
		},
	},
	maxCheckinDescriptionLength: 400,
	minEventPoints: 0,
	maxEventPoints: 100,
	icon: {
		svg: "/img/logos/acm.svg",
	},
	thumbnails: {
		default: "/img/thumbnails/default.png",
		maxSizeInBytes: 500000,
	},
} as const;

export const defaultTheme = "light";


const majors = [
	"Computer Science",
	"Accounting",
	"Accounting Technician",
	"Actuarial Science",
	"Aerospace/Aeronautical Engineering",
	"Agricultural Business & Management",
	"Agricultural Economics",
	"Agricultural Mechanization",
	"Agricultural Production",
	"Agricultural/Bioengineering",
	"American/English Literature",
	"Applied Mathematics",
	"Architectural Engineering",
	"Art History, Criticism & Conservation",
	"Art, General",
	"Astronomy",
	"Atmospheric Sciences & Meteorology",
	"Banking & Financial Support Services",
	"Biochemistry & Biophysics",
	"Biology, General",
	"Biomedical Engineering",
	"Business Administration & Management, General",
	"Business/Management Quantitative Methods, General",
	"Business/Managerial Economics",
	"Cell/Cellular Biology",
	"Chemical Engineering",
	"Chemistry",
	"Cinematography/Film/Vide Production",
	"Civil Engineering",
	"Classical/Ancient Languages & Literatures",
	"Comparative Literature",
	"Computer & Information Sciences, General",
	"Computer Engineering",
	"Computer Networking/Telecommunications",
	"Computer Software & Media Applications",
	"Computer System Administration",
	"Construction Engineering/Management",
	"Creative Writing",
	"Criminology",
	"Cyber Security",
	"Data Management Technology",
	"Dental Assisting",
	"Design & Visual Communications, General",
	"Ecology",
	"Economics",
	"Electrical Engineering",
	"Engineering (Pre-Engineering), General",
	"English Language & Literature, General",
	"Finance, General",
	"Financial Planning & Services",
	"Fine/Studio Arts",
	"Food Sciences & Technology",
	"Foreign Languages/Literatures, General",
	"French Language & Literature",
	"Genetics",
	"Geological & Earth Sciences",
	"Graphic Design",
	"Health Services Administration,General",
	"Human Resources Development/Training",
	"Human Resources Management",
	"Industrial Design",
	"Industrial Engineering",
	"Information Science",
	"Information Technology And Systems",
	"Insurance & Risk Management",
	"International Business Management",
	"International Relations & Affairs",
	"Investments & Securities",
	"Labor/Industrial Relations",
	"Law (Pre-Law)",
	"Legal Administrative Assisting/Secretarial",
	"Legal Studies, General",
	"Linguistics",
	"Logistics & Materials Management",
	"Management Information Systems",
	"Marine/Aquatic Biology",
	"Marketing Management & Research",
	"Mathematics, General",
	"Mechanical Engineering",
	"Medical Assisting",
	"Medical Office/Secretarial",
	"Medical Records",
	"Medical/Clinical Assisting, General",
	"Microbiology & Immunology",
	"Music, General",
	"Music, Theory & Composition",
	"Natural Resources Conservation, General",
	"Natural Resources Management",
	"Neuroscience",
	"Nuclear Engineering",
	"Occupational Therapy Assisting",
	"Philosophy",
	"Photography",
	"Physical Sciences, General",
	"Physical Therapy Assisting",
	"Physics",
	"Political Science & Government",
	"Psychology, Clinical & Counseling",
	"Psychology, General",
	"Public Speaking",
	"Sales, Merchandising, & Marketing, General",
	"Secretarial Studies & Office Administration",
	"Small Business Management/Operations",
	"Social Sciences, General",
	"Sociology",
	"Software Engineering",
	"Statistics",
	"Supply Chain Management",
	"Urban Studies/Urban Affairs",
	"Webpage Design",
	"Other",
] as const;

const bucketEventThumbnailBaseUrl = `${c.clubName}-${c.universityName}/event-thumbnails`;

export default c;
export {
	majors,
	bucketEventThumbnailBaseUrl,
}

	

